version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"  # Exposes MongoDB on port 27017
    volumes:
      - mongo-data:/data/db  # Volume to persist MongoDB data

volumes:
  mongo-data:
    driver: local