version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"  # Exposes MongoDB on port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db  # Volume to persist MongoDB data

  nestjs-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-backend
    restart: always
    ports:
      - "3000:3000"  # Exposes NestJS on port 3000
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/admin  # MongoDB connection URI for NestJS
    depends_on:
      - mongodb  # Ensures MongoDB is started before the NestJS service

volumes:
  mongo-data:
    driver: local
